<?php

namespace ContainerRs8Kl1k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContatosControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ContatosController' shared autowired service.
     *
     * @return \App\Controller\ContatosController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/ContatosController.php';
        include_once \dirname(__DIR__, 4).'/src/Helper/Validadores.php';
        include_once \dirname(__DIR__, 4).'/src/Helper/ExtratorDadosRequest.php';
        include_once \dirname(__DIR__, 4).'/src/Helper/EntidadeFactory.php';
        include_once \dirname(__DIR__, 4).'/src/Helper/Cacher.php';

        $a = ($container->privates['App\\Repository\\ContatosRepository'] ?? $container->load('getContatosRepositoryService'));

        return $container->services['App\\Controller\\ContatosController'] = new \App\Controller\ContatosController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), new \App\Helper\Validadores(), new \App\Helper\ExtratorDadosRequest(), $a, ($container->services['cache.app'] ?? $container->load('getCache_AppService')), new \App\Helper\EntidadeFactory($a), new \App\Helper\Cacher());
    }
}
