<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'index_HTML' => [[], ['_controller' => 'App\\Controller\\ControllerHtml::Index'], [], [['text', '/']], [], []],
    'AddContato_API' => [[], ['_controller' => 'App\\Controller\\ContatosController::NovoContato'], [], [['text', '/api/']], [], []],
    'listarContato_API' => [[], ['_controller' => 'App\\Controller\\ContatosController::buscarContatos'], [], [['text', '/api/contatos/']], [], []],
    'listarUmContato_API' => [['id'], ['_controller' => 'App\\Controller\\ContatosController::buscarUmContato'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/contatos']], [], []],
    'editarUmContato_API' => [['id'], ['_controller' => 'App\\Controller\\ContatosController::editarContato'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/contatos']], [], []],
    'excluirUmContato_API' => [['id'], ['_controller' => 'App\\Controller\\ContatosController::excluirContato'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/contatos']], [], []],
];
